name: "Create and promote release"
run-name: Create and promote release ${{ inputs.name }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Create release'
        default: ""
        required: true
      sec-file-and-chart:
        type: boolean
        description: 'Do not bump sec file and chart'
        default: false
      dry-run:
        type: boolean
        description: 'Do not publish'
        default: false

jobs:
  create-release:
    name: Create release
    uses: "./.github/workflows/create-release.yaml"
    with:
      name: ${{ inputs.name }}
      sec-file-and-chart: ${{ inputs.sec-file-and-chart }}
      dry-run: ${{ inputs.dry-run }}
    secrets: inherit

  promote:
    name: Promote
    needs: create-release
    uses: "./.github/workflows/promote-keb-to-dev.yaml"
    with:
      releaseTag: ${{ inputs.name }}
    secrets: inherit
